# This workflow runs automatically every Sunday at 00:00 UTC and creates a conda cache for the week.
# In addition, it runs on every push and pull request to main. It skips update dependencies step if cache exists.

name: tests

on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - '*'
    types: [ closed, opened, synchronize, reopened ]
  
  #schedule:
  #  - cron: '0 0 * * 0' # Run every Sunday at 00:00
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CACHE_NUMBER: 1  # increase to reset cache manually
  IMAGE_NAME: todolistapp

permissions: write-all

jobs:
  job1:

    # https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
    defaults:
      run:
        shell: bash -el {0}

    name: "Unit Testing"
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' || github.event_name == 'push' || ( github.event_name == 'pull_request' && github.event.pull_request.head.ref != 'main' )
    runs-on: ubuntu-22.04
    timeout-minutes: 30 # increasing timeout
    steps:
        - uses: actions/checkout@v2
              
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"
            architecture: "x64"
          env:
            AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
  
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
              
        - name: Run tests
          run: |
            python -m pytest TodoApp1/test
